security:
    encoders:
        App\Entity\User:
            algorithm: auto
    enable_authenticator_manager: true
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: apiToken
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
    access_control:
        - { path: ^/api, roles: ROLE_USER }
