---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: shooteram-cdn
  labels:
    app: shooteram-cdn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shooteram-cdn
  template:
    metadata:
      labels:
        app: shooteram-cdn
    spec:
      containers:
        - name: shooteram-cdn
          image: ghcr.io/shooteram/cdn
          env:
            - name: APP_ENV
              value: "prod"
            - name: APP_DEBUG
              value: "0"
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: symfony-shooteram-fr
                  key: shooteram-fr-symfony-env-secret
          ports:
            - name: web
              containerPort: 80
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
      imagePullSecrets:
        - name: ghcr-registry-secret
---
apiVersion: v1
kind: Service
metadata:
  name: shooteram-cdn
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: shooteram-cdn
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: shooteram-cdn
spec:
  rules:
    - host: cdn.shooteram.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shooteram-cdn
                port:
                  number: 80
  tls:
    - hosts:
        - cdn.shooteram.fr
      secretName: shooteram.fr
